spring:
  cloud:
    gateway:
      routes:
       - id: r1
         uri: http://localhost:8083/
         predicates:
         - Path= /service-patient/**
       - id: r2
         uri: http://localhost:8083/
         predicates:
         - Path= /rendezVous/**
       - id: r3
         uri: http://localhost:8083/
         predicates:
         - Path= /medecin-service/**
       - id: r4
         uri: http://localhost:8083/
         predicates:
         - Path= /consultation-service/**
       - id: r5
         uri: http://localhost:8082/
         predicates:
         - Path= /facturation-service/**




  application:
    name: gateway-service

server:
  port: 8888